- name: Install APT software
  become: yes
  apt:
    state: latest
    name:
      - sway
      - swaylock
      - swayidle
      - grim
      - bluez
      - rxvt-unicode-256color
      - rofi
      - waybar