- name: Install APT software
  become: yes
  apt:
    state: latest
    name:
      - vim
      - firefox
      - curl
      - jq
      - ssh
      - tree
      - locate

# Install a snap with classic confinement
- name: Install slack
  snap:
    name: slack
    state: present
    classic: yes